routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resources([
	'product' => 'ProductController',
	'product_category' => 'ProductCategoryController',
	'member_category' => 'MemberCategoryController',
	'member' => 'MemberController',
	'promo' => 'PromoController',
	'transaksi' => 'TransaksiController',
]);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function categoryRef()
    {
      return $this->belongsTo(ProductCategory::class, 'product_category_id');
    }
    public function pembeli()
    {
      return $this->hasMany(Transaksi::class, 'product_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductCategory;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Product::with('categoryRef')->get();
        return view('product.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = ProductCategory::all();
        return view('product.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
       $extension = $request->image->extension();
       $namafile = str_replace("-","",date("Y-m-d")).substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUFWXYZ'),1,3);
       $request->image->move(public_path('/uploads/products'), $namafile.'.'.$extension);

       $products = new Product;
       $products->name = $request->name;
       $products->image = $namafile.'.'.$extension;
       $products->product_category_id = $request->category;
       $products->desc = $request->desc;
       $products->price = $request->price;
       $products->save();
       return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $product = product::with('pembeli.categoryRef')->findorFail($product->id);
        return view('product.history', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $category = ProductCategory::all();
        return view('product.edit', compact('category', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $old = public_path()."/uploads/products/".$product->image;
        if(file_exists($old))
    {
        unlink($old);
    }
       $extension = $request->image->extension();
       $namafile = str_replace("-","",date("Y-m-d")).substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUFWXYZ'),1,3);
       $request->image->move(public_path('/uploads/products'), $namafile.'.'.$extension);

       $product->name = $request->name;
       $product->image = $namafile.'.'.$extension;
       $product->product_category_id = $request->category;
       $product->desc = $request->desc;
       $product->price = $request->price;
       $product->update();
       return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('product.index');
    }
}

resources/views/product/create.blade.php
@extends('layouts.template')

@section('content')

<div class="container">
<div class="x_panel">
    <div class="x_title">
     <h1 class="h3 mb-1 text-gray">Tambah Data Barang</h1>

<!-- DataTales Example -->


    <div class="card body">                           
    <form action="{{ route ('product.store') }}" method="post" enctype="multipart/form-data">
    @csrf 
    <form role="form">
         <div class="col-md-6">
            <div class="form-group">
                <label for="name">Nama</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Masukkan Nama Barang">
            </div>
            <br />
        <div class="form-group">
                <label for="image">Gambar</label>
                <input type="file" name="image" class="form-control" id="image" placeholder="Masukkan Gambar">
            </div>
        <div class="form-group">
                <label for="category">Produk Kategori</label>
                            <select class="form-control" id="category" name="category">
                            <option>chose...</option>
                                @foreach ($category as $item)
                                <option value="{{ $item->id }}"> {{ $item->name }}</option>
                                @endforeach
                        </select>
            </div>
        <div class="form-group">
                <label for="desc">Deskripsi</label>
                <input type="text" name="desc" class="form-control" id="desc" placeholder="Masukkan Deskripsi Barang">
            </div>
        <div class="form-group">
                <label for="price">Harga</label>
                <input type="text" name="price" class="form-control" id="price" placeholder="Masukkan Harga Barang">
            </div>
            <button type="submit" class="btn btn-danger">Simpan</button>
            <a href="/product" class="btn btn-warning">Kembali</a>
    </form>
    </div> 
    </div> 
    </div>
    </div>
                                     
@endsection

resources/views/product/edit.blade.php
@extends('layouts.template')

@section('content')

<div class="container">
<div class="x_panel">
    <div class="x_title">
     <h1 class="h3 mb-1 text-gray">Ubah Data Barang</h1>

<!-- DataTales Example -->


    <div class="card body">                           
    <form action="{{ route ('product.update', $product->id) }}" method="post" enctype="multipart/form-data">
    @csrf
    @method('put') 
    <form role="form">
         <div class="col-md-6">
            <div class="form-group">
                <label for="name">Nama</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Masukkan Nama Barang" value="{{ $product->name }}">
            </div>
            <br />
        <div class="form-group">
                <label for="image">Gambar</label>
                <input type="file" name="image" class="form-control" id="image" placeholder="Masukkan Gambar">
            </div>
        <div class="form-group">
                <label for="category">Produk Kategori</label>
                            <select class="form-control" id="category" name="category">
                            <option>chose...</option>
                                @foreach ($category as $item)
                                <option value="{{ $item->id }}" {{ $product->product_category_id == $item->id ? 'selected' : ''}}> {{ $item->name }}</option>
                                @endforeach
                        </select>
            </div>
        <div class="form-group">
                <label for="desc">Deskripsi</label>
                <input type="text" name="desc" class="form-control" id="desc" placeholder="Masukkan Deskripsi Barang" value="{{ $product->desc }}">
            </div>
        <div class="form-group">
                <label for="price">Harga</label>
                <input type="text" name="price" class="form-control" id="price" placeholder="Masukkan Harga Barang" value="{{ $product->price }}" rows="1">
            </div>
            <button type="submit" class="btn btn-danger">Simpan</button>
            <a href="/product" class="btn btn-warning">Kembali</a>
    </form>
    </div> 
    </div> 
    </div>
    </div>
                                     
@endsection

resources/views/product/history.blade.php
@extends('layouts.template')

@section('content')


     
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-1 text-gray">Pembelian</h1>

<!-- DataTales Example -->
<div class="card shadow mb-3">
  <div class="card-header py-2">
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr style="text-align: center;">
            <th>No</th>
            <th>No Transaksi</th>
            <th>Nama Lengkap</th>
            <th>Nama Product</th>
            <th>Kuantitas</th>
            <th>Diskon</th>
            <th>Total</th>
          </tr>
        </thead>
        
        <tbody>
              @foreach ($product->pembeli as $i => $item)
              <tr style="text-align: center;">
                  <td>{{ $i+1 }}</td>
                  <td>{{ $item->trx_number }}</td>
                  <td>{{ $item->categRef->full_name }}</td>
                  <td>{{ $item->categoryRef->name }}</td>
                  <td>{{ $item->quantity }}</td>
                  <td>{{ $item->discount }}</td>
                  <td>{{ $item->total }}</td>
              </tr>
              @endforeach
              </tbody>  
        
      </table>
    </div>
  </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.template')

@section('content')


     
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-1 text-gray">Barang</h1>

<!-- DataTales Example -->
<div class="card shadow mb-3">
  <div class="card-header py-2">
      <li>
        <a href="{{ route('product.create') }}">
          <button type="button" class="btn btn-primary btn-sm">Tambah</button>
        </a>
      </li>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr style="text-align: center;">
            <th>No</th>
            <th>Nama</th>
            <th>Gambar</th>
            <th>Produk_Kategori</th>
            <th>Deskripsi</th>
            <th>Harga</th>
            <th>Pilihan</th>
          </tr>
        </thead>
        
        <tbody>
              @foreach ($category as $i => $item)
              <tr style="text-align: center;">
                  <td>{{ $i+1 }}</td>
                  <td>{{ $item->name }}</td>
                  <td> <img src="{{ URL::to('/') }}/uploads/products/{{$item->image}}"
                  class="img-thumbnail" width="100px" height="100px" /></td>
                  <td>{{ $item->categoryRef->name }}</td>
                  <td>{{ $item->desc }}</td>
                  <td>{{ $item->price }}</td>
                  <td>
                    <form action="{{ route('product.destroy',$item->id) }}" method="post">
                    <a href="{{ route('product.edit',$item->id) }}" class="btn btn-success btn-circle"><i class="fas fa-edit"></i>
                    </a>
                    @csrf 
                    @method('delete')
                      <button type="submit" class="btn btn-danger btn-circle" 
                      onclick="return confirm('Yakin Nih Dihapus ?')"><i class="fas fa-trash"></i></button>
                      <a href="{{ route('product.show',$item->id) }}" class="btn btn-info btn-circle">
                    <i class="fas fa-list"></i>
                       </a>
                    </form>

                    </form>
                </td>
              </tr>
              @endforeach
              </tbody>  
        
      </table>
    </div>
  </div>
</div>
@endsection